site_name: IMPTOX XAI
source: docs
repo_url: https://github.com/ThibaultSchowing/IMPTOX_XAI
theme:
  name: material
  logo: assets/img/imptox-rgb.jpg
  icon:
    repo: fontawesome/brands/github
    admonition:
      example: fontawesome/solid/flask
  favicon: assets/favicon/imptox-rgb_white.ico
  features:
    - navigation.footer

  font:
    text: Merriweather Sans
    code: Red Hat Mono
  palette:
    primary: custom
    # Dark Mode
    #- scheme: slate
    #  toggle:
    #    icon: material/weather-sunny
    #    name: Dark mode
    #  primary: green
    #  accent: deep purple

    # Light Mode
    #- scheme: default
    #  toggle:
    #    icon: material/weather-night
    #    name: Light mode
    #  primary: blue
    #  accent: deep orange

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic

  - pymdownx.tabbed:
      alternate_style: true

  - admonition
  - pymdownx.details
  - pymdownx.superfences

  - tables

extra:
  social:
    - icon: simple/youtube
      link: https://www.youtube.com/@imptoxproject
